### ISSUE TITLE
creating a new CM with identification method use unit name gives wrong name in one field

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#470]
The created thing itself is just fine, but at the moment of creation it puts the actual unintelligible UID in the USTP#. If I go back to the list of CM, and click on this record again the list looks right, but clicking into individual records the USTP# continues to come up the UID (except for the first created record, which is correctly labeled USTP# SU-1).
![image](https://user-images.githubusercontent.com/49291909/75125156-c2f7a180-5681-11ea-97e9-388faecb838e.png)

**Comment by urapadmin** [comment]
I cannot reproduce that. Can you still reproduce it? If so, please try to describe your steps to the issue again.

**Comment by lbestock** [comment]
I can still reproduce it, but only in the Survey Unit in which the problem first occurred. Other Survey Units with the same parameters (also transects, also with default identification method CM setting) produce the right kind of number. New numbers in that unit are still produced wonkily. My sequence of events creating the unit I can no longer reconstruct. The sequence of events creating collected material within it is standard: select unit from home page, go to CM tab, click plus button.

I have now entered previously created survey units, and created new ones (both transect and survey), and in none of them does the same function misbehave this way.

**Comment by urapadmin** [comment]
let's keep this open and see if it occurs again anywhere else when you test real archaeological scenarios. I also suggest we start with a clean ustp before the test (I have to do clean it).

**Comment by lbestock** [comment]
Reproduced: you suspect it has to do with having all the CM named the same thing.  Also produced issues using the back button at repeated stages. I have uploaded the file to the USTP server but not imported it.

**Comment by urapadmin** [comment]
I have not really attended to this but there was a bad bug when going from locus to collected material. The unit got lost on the way. That is fixed now. It could be that it also caused this phenomenon here. Please try v8.9.10.

**Comment by lbestock** [comment]
Still happening in v.8.9.11:
![image](https://user-images.githubusercontent.com/49291909/79074297-93e0d200-7cb9-11ea-9807-69ad05da25e9.png)

**Comment by lbestock** [comment]
Also happening in an excavation unit:
![image](https://user-images.githubusercontent.com/49291909/79074825-7cefaf00-7cbc-11ea-84b2-86dfe2b0ac34.png)

Also happening in another just created excavation unit.

**Comment by urapadmin** [comment]
hm. Even in your own file I have trouble seeing these things. What is your filemaker version?

**Comment by urapadmin** [comment]
I know, you already did that, but can you please give me that database again?

**Comment by urapadmin** [comment]
### fixed in v8.9.15
ja, that is a result of a having many the same collected material identifiers. The only way to deal with it is to show more than the identifier in the list so that all the collected materials have distinct list entries. 

- [ ] That is why we now have the new config key "show_cm_selection_with_material". It includes the material type in the list and thus makes the items distinguishable. 

- [ ] For those cases where even that does not help (who knows what strange projects are out there)... we can give up on the list up there entirely with "show_cm_selection" and simply show the locus id but not make it selectable.

**Comment by lbestock** [comment]
A case where I'm not sure if I need a new ticket, but I think not because it is still the same issue.
The new configuration keys are there and the first one works fine if the ID method for CM is serial number per device. But if I set the ID method to "just use context again" (which is where the problem lies), then once more the first created CM looks proper (and includes the material) but the second does not. Not only does it still display the wonky UID instead of the context (which if I understand you correctly it will always do - no way around it), it does NOT show the material like it's supposed to:
![image](https://user-images.githubusercontent.com/49291909/80132375-92d95b80-8569-11ea-91ac-51e4e95b7fae.png)

**Comment by lbestock** [comment]
(Argh still signed in as admin. I swear I was going back and forth from admin to LDB a ton! Just forgot to go back this time.)

**Comment by urapadmin** [comment]
I don't understand. If you have a project that produces similar collected material numbers you must use "show_cm_selection_with_material" set. Otherwise the wonky identifier will show and there will be only one identifier in the selection. I am not sure, though, what you mean with it does not show the material like it used to. What is wrong about it (apart from the fact that we talk about something that is not supposed to be done here, anyhow)?

**Comment by lbestock** [comment]
In the above test, "show_cm_selection_with_material" was set to yup. And the ID method for CM was "just use context again". I created two CM in that context:
![image](https://user-images.githubusercontent.com/49291909/80138619-0fbd0300-8573-11ea-9274-27ef4f6f58b9.png)
When I go into those, the leather (created first) looks as I expected:
![image](https://user-images.githubusercontent.com/49291909/80138690-2e22fe80-8573-11ea-958f-8f0f08c81bea.png)
The metal (created second) looks as the screen shot above, so in the banner it displays the UID rather than the context and it does NOT say (metal) and I thought that "show_cm_selection_with_material" was supposed to make it say (metal) (as it does (leather) in the previously created CM in the same context).

**Comment by lbestock** [comment]
Also I just created a third one with yet another CM type, and same thing. From all of them, when I click on the drop down menu I am not given a list of all the created CMs but only the ability to choose the one that is properly named, in this case 0026 (leather). 
![image](https://user-images.githubusercontent.com/49291909/80138976-b6090880-8573-11ea-9a54-dbcfe8d9f313.png)

**Comment by urapadmin** [comment]
### fixed in v8.9.18

**Comment by lbestock** [comment]
Aaaa that's very exciting!

**Comment by urapadmin** [comment]
This still happens. Now in s'Urachi.

**Comment by urapadmin** [comment]
no, it does not, except when one has the same material selected twice. This is still really a bad solution for the problem.

**Comment by lbestock** [comment]
This is what's happening in USTP, too, of course. Shall we close it? I think so. It works properly for this type of collected materials numbering, which should not have two bags of ceramics at all.
