### ISSUE TITLE
change image container in locus relations to new handling

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#498]
I think I forgot the locus relation image container.

**Comment by urapadmin** [comment]
### @test v8.9.9
I had forgotten the locus relation image container in the last versions. Please apply the tests for image containers to this one as well. 
  - Special here is that after having created a relation with an image that image should be found when searching for any of the two loci involved in the relationship.

**Comment by SamKimball-BrownU** [comment]
The image only appears in the locus that it was first uploaded in (i.e., if the relationship is created between 001 and 002, while in 001, the image only shows up in 001)

However, it DOES appear under both tags when searching in gallery. So, searching for SKK-001 brings up both, and searching for SKK-002 works for both.

**Comment by urapadmin** [comment]
Please move test cases with issues to the "back to developer" pane of the "testing" project. You can use the little dropdown under the project name in this view here. That makes it a little easier for me to find failed tests.

**Comment by SamKimball-BrownU** [comment]
Sorry! I was in the middle of testing but I should have probably just put it in "back to developer" so that you could get to work on it

**Comment by urapadmin** [comment]
my mistake, if you were still testing this. In that case "in test" is fine (I have set it back to that status).

**Comment by SamKimball-BrownU** [comment]
Sorry I am just getting back to this, but confirmed that the problem persists using all input methods.

**Comment by urapadmin** [comment]
fixed in v8.9.10
There was still a lot wrong with this relation image thing and I have spend quite some time on it now. Please test it again thoroughly. even those things that worked so far, please. I might have messed it up now in a different way.

**Comment by SamKimball-BrownU** [comment]
Tested under: USTP 8.9.11, Windows 10

Issue: context relation photos are not searchable in image gallery. It seems they are given no identifiers. However, it still shows up, just with no information attached.
![image](https://user-images.githubusercontent.com/61027113/79053347-46edf480-7c02-11ea-9085-7cac94718150.png)

When relation images are changed, it shows up correctly under both contexts. It remains unsearchable in the gallery. It also deletes and replaces (presumably permanently) the previous photo in the gallery.
![image](https://user-images.githubusercontent.com/61027113/79053439-f6c36200-7c02-11ea-8ad0-4d432e436bfc.png)

When relations are deleted, the counterpart is also deleted. The image still remains in the gallery (although still without any identifiers)
![image](https://user-images.githubusercontent.com/61027113/79053486-54f04500-7c03-11ea-935f-9228ce62a33c.png)

After that relation is deleted and I try to add another one, the previous relation photo stays in the gallery and another one is added, again with no identifiers.

This seems to all be one technical issue, just manifesting in different ways.

**Comment by urapadmin** [comment]
### @8.9.18 should be final now
new image handling with drag & drop etc. now in place for locus photos, too. I also updated the image description for image tests once more, mainly to give an example what things look like if they are correct: https://www.meritaten.net/urapdev/doku.php?id=how_to_test_an_image_container#what_to_test

**Comment by SamKimball-BrownU** [comment]
issue: when adding images via gallery, the screen flashes several times. This may be a limitation of filemaker. Also, if you had previously added an image to that container via drag and drop, then it will display the drag and drop warning when adding via gallery.

Otherwise, everything is working as intended

**Comment by urapadmin** [comment]
reopened because image proxy was not set correctly.

**Comment by urapadmin** [comment]
### v9.1
horrors.

**Comment by urapadmin** [comment]
adding from the gallery changes proxy - that should not happen!
