### ISSUE TITLE
admin delete narrative followed by inability to make new narrative

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#573]
A relic of #486 which is otherwise finished (and has been closed).

Ran into it in URAP 8.9.18 but tested again with USTP v.9 (!!) to make sure it's still there and it is.

As admin I can delete narratives properly. But there is a small hiccup when I then create a new narrative. If I delete the narrative and immediately try to create a new one in the same unit, the screen flashes (on Alice) but does not give me a blank new narrative, the screen has the last narrative (not the deleted one - that's gone) still present. That the new narrative WAS created is clear - if I leave the unit and come back the top narrative is blank (and there are however many blank narratives as there were times I hit the + button). I just can't see them until I have left and reentered.

**Comment by urapadmin** [comment]
### 9.2.1 
fixed

**Comment by luizaogs** [comment]
Hmm I am still having the same issue exactly as described here (as admin, on 9.4.3).

**Comment by urapadmin** [comment]
in both simple and full excavation?

**Comment by luizaogs** [comment]
AH no, full excavation is fine. Only in simple.

**Comment by urapadmin** [comment]
ok. a classic. I forgot about doing the same think in simple excavation. I wish we could get rid of one of them.

**Comment by urapadmin** [comment]
### 9.4.4
should work in simple excavating now, too.
