### ISSUE TITLE
background window popping up in locus relations

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#801]
Related to #800. After getting a message that the locus relation "rests against" doesn't have an inverse relationship, the following happened when I tried to insert an image for that relationship: 

![image](https://user-images.githubusercontent.com/67970402/88853408-afff7500-d1bd-11ea-9a5c-e01f140a956f.png)

After clicking on "cancel," I got this: 

![image](https://user-images.githubusercontent.com/67970402/88853416-b1c93880-d1bd-11ea-984a-fb8f42af8f77.png)

The image did show up eventually when I clicked outside of the image container. 

I figure that this is the case because the inverse relationship hasn't been configured (indeed it does not show up for the other locus) but it seems buggy regardless.

**Comment by urapadmin** [comment]
ja, these things should never happen even if the configuration is missing something.

**Comment by urapadmin** [comment]
### 9.5
fixed in the way that the ugly window is not left open and you just get a message that the inverse relation cannot be updated.

**Comment by luizaogs** [comment]
Just for the record -- the image still gets added to the original relation (obviously not to the inverse relation that doesn't exist).
